name: gh pages

on:
  push:
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  texlive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install TeX Live
        uses: zauguin/install-texlive@v4
        with:
          packages: >
            package_file: tl_packages
      - run: make passierschein-a38.pdf
      - name: Prepare public/
        run: |
          mkdir public
          mv passierschein-a38.pdf public/
      - name: Publish
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
